[
    "MediaWiki:Gadget-HotCat.js",
    "MediaWiki:Gadget-rollback-summary.js",
    "User:AnnAngela/js/userStatus.js",
    "User:星海子/js/usergroup.js",
    "User:AnnAngela/js/QuickSaveDraft.es2015.js",
    "User:Leranjun/js/MoveToUserSubpage.js",
    "User:Leranjun/js/ScrollToBottom.js",
    "User:Leranjun/js/FlagForDeletion.js",
]
